services:
  proxy:
    depends_on:
      - web
    image: nginx:alpine
    entrypoint:
        ["/bin/sh", "/app/scripts/proxy/dev_entrypoint.sh"]
    environment:
      USE_HTTPS: ${USE_HTTPS}
      PROXY_PORT_HTTP: ${PROXY_PORT_HTTP}
      PROXY_PORT_HTTPS: ${PROXY_PORT_HTTPS}
      WEB_HOSTNAME: ${WEB_HOSTNAME}
      WEB_PORT: ${WEB_PORT_HTTP}
    ports:
      - "${LOCAL_PORT_HTTP}:${PROXY_PORT_HTTP}"
      - "${LOCAL_PORT_HTTPS}:${PROXY_PORT_HTTPS}"
    volumes:
      - ./scripts:/app/scripts
      - ${CERTS_PATH}:/etc/letsencrypt:ro
    networks:
      - dev_network

  web:
    depends_on:
      - db
    image: "horsecatdog/bedrock:latest"
    build: !reset null
    entrypoint:
        ["/bin/sh", "/app/scripts/web/dev_entrypoint.sh"]
    environment:
      BEDROCK_ROOT: "/www/srv"
      DEV_GROUP_ID: ${DEV_GROUP_ID}
      WORDPRESS_DB_HOST: "db:3306"
      WORDPRESS_DB: ${WORDPRESS_DB}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password_dev
      WEB_HOSTNAME: ${WEB_HOSTNAME}
      WEB_PORT: ${WEB_PORT_HTTP}
      WEB_PROTOCOL: ${WEB_PROTOCOL}
      PROJECTS_DIR: ${PROJECTS_DIR}
      PROJECT: ${PROJECT}
      THEME: ${THEME}
    volumes:
      - ${PROJECTS_DIR}:/www/srv
      - ./scripts:/app/scripts
    secrets:
      - db_password_dev
    networks:
      - dev_network
    expose:
      - "5173"
      - "${WEB_PORT_HTTP}"

  db:
    image: "mariadb:latest"
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password_dev
      MARIADB_DATABASE: wordpress_dev
      MARIADB_USER: wordpress_dev
      MARIADB_PASSWORD_FILE: /run/secrets/db_password_dev
    volumes:
      - mariadb_dev_data:/var/lib/mysql
    secrets:
      - db_password_dev
      - db_root_password_dev
    expose:
      - "3306"
    networks:
      - dev_network

volumes:
  mariadb_dev_data:

networks:
  dev_network:
    driver: bridge

secrets:
  db_password_dev:
    file: ${DB_WORDPRESS_PASSWORD_FILE}
  db_root_password_dev:
    file: ${DB_ROOT_PASSWORD_FILE}
